"""Markdown report generator."""

from __future__ import annotations

from datetime import datetime
from pathlib import Path
from typing import Any, Optional

from ..storage.database import Database
from ..storage.models import Idea, Paper, TrendKeyword


class MarkdownReport:
    """Generate Markdown reports."""

    def __init__(self, db: Database, output_dir: str | Path):
        """Initialize report generator.

        Args:
            db: Database instance
            output_dir: Output directory for reports
        """
        self.db = db
        self.output_dir = Path(output_dir)
        self.output_dir.mkdir(parents=True, exist_ok=True)

    def generate_daily_report(
        self,
        date: Optional[str] = None,
        papers: Optional[list[Paper]] = None,
        ideas: Optional[list[Idea]] = None,
        trends: Optional[list[TrendKeyword]] = None,
    ) -> str:
        """Generate daily Markdown report.

        Args:
            date: Date string (YYYY-MM-DD)
            papers: List of papers (fetched from DB if None)
            ideas: List of ideas (fetched from DB if None)
            trends: Trend keywords (fetched from DB if None)

        Returns:
            Path to generated report
        """
        date = date or datetime.now().strftime("%Y-%m-%d")

        # Fetch data if not provided
        if papers is None:
            papers = self.db.get_recent_papers(days=1, limit=100)

        if ideas is None:
            ideas = self.db.get_top_ideas(limit=10)

        if trends is None:
            trends = self.db.get_keyword_trends(days=7)

        # Build report
        lines = [
            f"# 📜 PaperPulse 每日报告 - {date}",
            "",
            f"> 🤖 发现 **{len(papers)}** 篇新论文 | 生成 **{len(ideas)}** 个创新 IDEA",
            "",
            "---",
            "",
        ]

        # Statistics
        stats = self.db.get_stats()
        lines.extend(self._build_stats_section(stats))

        # Trends
        if trends:
            lines.extend(self._build_trends_section(trends))

        # Top papers
        if papers:
            lines.extend(self._build_papers_section(papers[:10]))

        # Ideas
        if ideas:
            lines.extend(self._build_ideas_section(ideas))

        # Footer
        lines.extend([
            "---",
            "",
            f"*Generated by PaperPulse at {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}*",
            "",
        ])

        # Write report
        report_path = self.output_dir / f"daily_{date}.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")

        return str(report_path)

    def _build_stats_section(self, stats: dict[str, Any]) -> list[str]:
        """Build statistics section."""
        return [
            "## 📊 今日概览",
            "",
            "| 指标 | 数值 |",
            "|------|------|",
            f"| 总论文数 | {stats.get('total_papers', 0)} |",
            f"| 已下载 | {stats.get('downloaded_papers', 0)} |",
            f"| 已分析 | {stats.get('analyzed_papers', 0)} |",
            f"| 生成 IDEA | {stats.get('total_ideas', 0)} |",
            "",
        ]

    def _build_trends_section(self, trends: list[TrendKeyword]) -> list[str]:
        """Build trends section."""
        lines = [
            "## 🔥 热门关键词",
            "",
            "| 关键词 | 论文数 | 趋势 |",
            "|--------|--------|------|",
        ]

        for t in trends[:10]:
            trend_icon = "↑" if t.trend_percent > 0 else "↓" if t.trend_percent < 0 else "→"
            lines.append(f"| {t.keyword} | {t.count} | {trend_icon} {abs(t.trend_percent):.0f}% |")

        lines.append("")
        return lines

    def _build_papers_section(self, papers: list[Paper]) -> list[str]:
        """Build papers section."""
        lines = [
            "## 📄 重点论文 (Top 10)",
            "",
        ]

        for i, paper in enumerate(papers, 1):
            lines.extend([
                f"### {i}. [{paper.title}]({paper.url})",
                "",
            ])

            arxiv_str = f"**arXiv**: {paper.arxiv_id} | " if paper.arxiv_id else ""
            lines.append(f"{arxiv_str}**领域**: {paper.venue or 'N/A'} | ⭐ 推荐指数: {min(10, paper.citation_count / 100 + 5):.1f}")
            lines.append("")

            # Abstract (truncated)
            if paper.abstract:
                abstract = paper.abstract[:200] + "..." if len(paper.abstract) > 200 else paper.abstract
                lines.append(f"> {abstract}")
                lines.append("")

            # Innovations
            if paper.innovations:
                lines.append("**创新点**:")
                for innovation in paper.innovations[:3]:
                    lines.append(f"- {innovation}")
                lines.append("")

            # Keywords
            if paper.keywords:
                lines.append(f"**关键词**: {', '.join(f'`{k}`' for k in paper.keywords[:5])}")
                lines.append("")

        return lines

    def _build_ideas_section(self, ideas: list[Idea]) -> list[str]:
        """Build ideas section."""
        lines = [
            "## 💡 今日推荐 IDEA",
            "",
        ]

        for i, idea in enumerate(ideas, 1):
            score_stars = "⭐" * int(idea.score * 5)
            lines.extend([
                f"### #{i} [{self._score_label(idea.score)}] {idea.title}",
                "",
                f"| 维度 | 评分 |",
                f"|------|------|",
                f"| 新颖性 | {idea.novelty_score:.2f} |",
                f"| 可行性 | {idea.feasibility_score:.2f} |",
                f"| 影响力 | {idea.impact_score:.2f} |",
                f"| **综合评分** | **{idea.score:.2f}** {score_stars} |",
                "",
            ])

            if idea.description:
                lines.append(f"**描述**: {idea.description[:300]}..." if len(idea.description) > 300 else f"**描述**: {idea.description}")
                lines.append("")

            if idea.related_paper_ids:
                lines.append(f"**相关论文**: {len(idea.related_paper_ids)} 篇")
                lines.append("")

            lines.append(f"**一键研究**: `paperpulse research {idea.idea_id}`")
            lines.append("")

        return lines

    def _score_label(self, score: float) -> str:
        """Get score label."""
        if score >= 0.8:
            return "高价值"
        elif score >= 0.6:
            return "中等"
        else:
            return "探索性"

    def generate_weekly_report(
        self,
        start_date: Optional[str] = None,
    ) -> str:
        """Generate weekly summary report."""
        # Get weekly data
        papers = self.db.get_recent_papers(days=7, limit=200)
        ideas = self.db.get_top_ideas(limit=20)
        trends = self.db.get_keyword_trends(days=7)

        date = datetime.now().strftime("%Y-%m-%d")

        lines = [
            f"# 📜 PaperPulse 周报 - {date}",
            "",
            f"> 本周收集 **{len(papers)}** 篇论文 | 生成 **{len(ideas)}** 个 IDEA",
            "",
            "---",
            "",
        ]

        # Top trends
        lines.extend([
            "## 📈 本周热门趋势",
            "",
        ])

        for t in trends[:15]:
            trend_icon = "↑" if t.trend_percent > 0 else "↓"
            lines.append(f"- **{t.keyword}**: {t.count} 篇 ({trend_icon} {abs(t.trend_percent):.0f}%)")

        lines.append("")

        # Top ideas
        lines.extend([
            "## 💡 本周最佳 IDEA",
            "",
        ])

        for i, idea in enumerate(ideas[:5], 1):
            lines.append(f"{i}. **{idea.title}** (评分: {idea.score:.2f})")
            if idea.description:
                lines.append(f"   {idea.description[:100]}...")
            lines.append("")

        # Footer
        lines.extend([
            "---",
            "",
            f"*Generated by PaperPulse*",
            "",
        ])

        # Write report
        report_path = self.output_dir / f"weekly_{date}.md"
        report_path.write_text("\n".join(lines), encoding="utf-8")

        return str(report_path)